In [4]:
import os
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:,.4f}'.format
pd.options.display.max_columns = 1000

In [2]:
# Calculate Data Extraction Logic from KB Housing File
def Extracting_IndexValue(type_names, region_names, sheet_names, selected_names, sheet_val, col_val):
    import itertools
    col_names = ['Time']
    for combination in itertools.product(region_names, type_names):
        col_names.append(combination[0]+':'+combination[1])

    col_logic = ['='+sheet_names[0]+'!A5']
    for combination in itertools.product(selected_names, sheet_names):
        col_logic.append('='+combination[1]+'!'+combination[0])
    index_val = pd.DataFrame(col_logic, index=col_names).T

    val_index = []
    for combination in itertools.product(sheet_val, col_val):
        val_index.append('='+combination[0]+'!'+combination[1])
    value = pd.DataFrame(val_index, index=col_names[1:]).T
    return index_val, value

type_names = ['Apartments(HPI)', 'Detached_Houses(HPI)', 'Row_Houses(HPI)']
region_names = ['Seoul', 'Northern Seoul', 'Southern Seoul', '6 Large Cities', 'Gyeonggi-do', 'Gangwon-do', 'Chungcheongbuk-do', 'Chungcheongnam-do ', 
                'Jeollabuk-do', 'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Non-Metropolitan Area']
sheet_names = ['매매APT', '매매단독', '매매연립']
selected_names = ['C5', 'D5', 'S5', 'AE5', 'CJ5', 'EE5', 'EI5', 'EQ5', 'FA5', 'FG5', 'FL5', 'FS5', 'GG5']
sheet_val = ['평균매매']
col_val = ['I125', 'J125', 'K125', 'M125', 'N125', 'O125', 'Q125', 'R125', 'S125', 'U125', 'V125', 'W125', 'AU125', 'AV125', 'AW125', 
               'AY125', '_125', '_125', 'BA125', '_125', '_125', 'BC125', '_125', '_125', 'BE125', '_125', '_125', 'BG125', '_125', '_125', 
               'BI125', '_125', '_125', 'BK125', '_125', '_125', 'BM125', 'BN125', 'BO125']
HPI_index, HPI_value = Extracting_IndexValue(type_names, region_names, sheet_names, selected_names, sheet_val, col_val)

type_names = ['Apartments(JDI)', 'Detached_Houses(JDI)', 'Row_Houses(JDI)']
region_names = ['Seoul', 'Northern Seoul', 'Southern Seoul', '6 Large Cities', 'Gyeonggi-do', 'Gangwon-do', 'Chungcheongbuk-do', 'Chungcheongnam-do ', 
                'Jeollabuk-do', 'Jeollanam-do', 'Gyeongsangbuk-do', 'Gyeongsangnam-do', 'Non-Metropolitan Area']
sheet_names = ['전세APT', '전세단독', '전세연립']
selected_names = ['C5', 'D5', 'S5', 'AE5', 'CJ5', 'EE5', 'EI5', 'EQ5', 'FA5', 'FG5', 'FL5', 'FS5', 'GG5']
sheet_val = ['평균전세']
col_val = ['I95', 'J95', 'K95', 'M95', 'N95', 'O95', 'Q95', 'R95', 'S95', 'U95', 'V95', 'W95', 'AU95', 'AV95', 'AW95', 
               'AY95', '_95', '_95', 'BA95', '_95', '_95', 'BC95', '_95', '_95', 'BE95', '_95', '_95', 'BG95', '_95', '_95', 
               'BI95', '_95', '_95', 'BK95', '_95', '_95', 'BM95', 'BN95', 'BO95']
JDI_index, JDI_value = Extracting_IndexValue(type_names, region_names, sheet_names, selected_names, sheet_val, col_val)
JDI_value

In [18]:
# Data Loading
location = 'C:\\Users\\KK\\Desktop\\20190102_KB주택가격동향_KK.xlsx'
raw_HPI = pd.read_excel(location, sheet_name='Raw_HPI_value')
raw_JDI = pd.read_excel(location, sheet_name='Raw_JDI_value')

raw_JDI.head()

,Time,Seoul:Apartments(HPI),Seoul:Detached_Houses(HPI),Seoul:Row_Houses(HPI),Northern Seoul:Apartments(HPI),Northern Seoul:Detached_Houses(HPI),Northern Seoul:Row_Houses(HPI),Southern Seoul:Apartments(HPI),Southern Seoul:Detached_Houses(HPI),Southern Seoul:Row_Houses(HPI),6 Large Cities:Apartments(HPI),6 Large Cities:Detached_Houses(HPI),6 Large Cities:Row_Houses(HPI),Gyeonggi-do:Apartments(HPI),Gyeonggi-do:Detached_Houses(HPI),Gyeonggi-do:Row_Houses(HPI),Gangwon-do:Apartments(HPI),Gangwon-do:Detached_Houses(HPI),Gangwon-do:Row_Houses(HPI),Chungcheongbuk-do:Apartments(HPI),Chungcheongbuk-do:Detached_Houses(HPI),Chungcheongbuk-do:Row_Houses(HPI),Chungcheongnam-do :Apartments(HPI),Chungcheongnam-do :Detached_Houses(HPI),Chungcheongnam-do :Row_Houses(HPI),Jeollabuk-do:Apartments(HPI),Jeollabuk-do:Detached_Houses(HPI),Jeollabuk-do:Row_Houses(HPI),Jeollanam-do:Apartments(HPI),Jeollanam-do:Detached_Houses(HPI),Jeollanam-do:Row_Houses(HPI),Gyeongsangbuk-do:Apartments(HPI),Gyeongsangbuk-do:Detached_Houses(HPI),Gyeongsangbuk-do:Row_Houses(HPI),Gyeongsangnam-do:Apartments(HPI),Gyeongsangnam-do:Detached_Houses(HPI),Gyeongsangnam-do:Row_Houses(HPI),Non-Metropolitan Area:Apartments(HPI),Non-Metropolitan Area:Detached_Houses(HPI),Non-Metropolitan Area:Row_Houses(HPI)
0,86.1000,"4,522.0677","10,565.6328","3,455.1281","3,998.0405","9,027.3738","3,333.3627","5,176.5320","13,463.3269","3,577.1910","2,522.9227","4,173.6333","1,524.8907",0.0000,0.0000,0.0000,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,0.0000,0.0000
1,2.0000,"4,713.3334","10,688.2514","3,472.5783","4,044.9383","9,009.6731","3,374.9258","5,436.8901","13,845.0848","3,577.1910","2,536.2013","4,182.9912","1,524.8907",0.0000,0.0000,0.0000,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,0.0000,0.0000
2,3.0000,"4,877.2755","10,994.7978","3,559.8290","4,150.4585","9,275.1841","3,433.1142","5,620.6723","14,277.7437","3,696.1257","2,589.3154","4,267.2125","1,596.6502",0.0000,0.0000,0.0000,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,0.0000,0.0000
3,4.0000,"4,986.5702","11,240.0349","3,638.3546","4,220.8052","9,505.2936","3,474.6773","5,773.8241","14,583.1499","3,815.0604","2,635.7903","4,314.0021","1,614.5901",0.0000,0.0000,0.0000,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,0.0000,0.0000
4,5.0000,"5,027.5557","11,240.0349","3,690.7050","4,291.1520","9,487.5929","3,582.7414","5,789.1393","14,583.1499","3,824.2093","2,642.4296","4,332.7180","1,614.5901",0.0000,0.0000,0.0000,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,nan,nan,0.0000,0.0000,0.0000

In [ ]:
%% 데이터 기초분석 및 정리 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[data,~,data_total] = xlsread('F:\Course\6.SamsungElectronics\Research\Managing Bubble Risks in Housing Market A Real Option Approach\Data\20180318_Raw.xlsx');
data(:,4) = data(:,4)/10000;
data(:,5) = data(:,5)/10000;
[mm,nn] = size(data);
date_full = data_total(2:mm+1,1);
[data_need, basic_statistics, hypothesis_result] = Data_Statistics_Default(data);
[data_vol] = xlsread('F:\Course\6.SamsungElectronics\Research\Managing Bubble Risks in Housing Market A Real Option Approach\Data\20180325_Raw_Volatility.csv');
% abs(return)을 변동성을 사용할 때
% data_vol = abs(data_need(:,4));
past_period = 3;
if length(data) == length(data_vol)
    data_loss = past_period;
else
    data_loss = length(data) - length(data_vol);
end

format long;
raw = [data(:,4) data_need(:,4)/100];
raw(:,4) = data_vol/100;
deltat = 1;
for i = data_loss+1 : length(raw)
    raw(i,3) = mean(raw(i-data_loss:i,2));
    raw(i,5) = raw(i,3) - (0.5)*power(raw(i,4),2);
    raw(i,6) = exp(raw(i,5)*deltat + raw(i,4)*deltat);
    raw(i,7) = exp(raw(i,5)*deltat - raw(i,4)*deltat);
end
[K_real] = data(:,5)';
[R_real] = data(:,3)';
R_real = (R_real/(100*12));

%% 주택가격 심플 트리 분석 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initial_year = input('초기년도 = ');
% initial_month = input('초기월 = ');
% final_year = input('만기년도 = ');
% final_month = input('만기월 = ');
% interval = input('interval = ');
% early_exercise = input('조기행사 유무? (1=Yes, otherwise=No) = ');
initial_year = 1988;
initial_month = 1;
final_year = 2017;
final_month = 12;
interval = 12;
early_exercise = 0;
initial = (initial_year - year(date_full(1,1))) * 12 + initial_month;
final = (final_year - year(date_full(1,1))) * 12 + final_month;
if (final-initial) < interval
    disp('Out of Bound!!');
    return;
end

%% 주택가격 데이터 전개 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
zz = 0;
for t = initial : interval : final-interval
    zz = zz + 1;
    T = t+interval;
    S_real = raw(:,1)';
    S = NaN(2^(T-t),T-t+1);
    S(1,1) = S_real(1,t);
    initial_spread = S_real(1,t) - K_real(1,t);
    for i = 2 : T-t+1
        for j = 1 : 2^(i-1)
            if mod(j,2) == 1
                z = 6;
            else
                z = 7;
            end
            S(j,i) = S(ceil(j/2),i-1) * raw(t+(i-2),z);
        end
    end

    V_call = zeros(size(S,1), size(S,2));
    V_put = zeros(size(S,1), size(S,2));
    earlyV1 = zeros(size(S,1), size(S,2)-1);
    earlyV2 = zeros(size(S,1), size(S,2)-1);
    earlyT1 = 0;
    earlyT2 = 0;
    for i = size(S,1) : -1 : 1
        V_call(i,size(S,2)) = S(i,size(S,2)) - K_real(1,T) - initial_spread;
        V_put(i,size(S,2)) = S(i,size(S,2)) - K_real(1,T) - initial_spread;
    end

    for j = 1 : size(S,2)-1
        for i = 1 : 2^(size(S,2)-(j+1))
            V_call(i,size(S,2)-j) = (0.5*V_call(2*i-1,size(S,2)-(j-1)) + 0.5*V_call(2*i,size(S,2)-(j-1))) / exp(R_real(1,T-(j-1)));
            V_put(i,size(S,2)-j) = (0.5*V_put(2*i-1,size(S,2)-(j-1)) + 0.5*V_put(2*i,size(S,2)-(j-1))) / exp(R_real(1,T-(j-1)));            
        
            if early_exercise == 1
                earlyV1(i, size(S,2)-j) = S(i,size(S,2)-j) - K_real(1,T-j) - initial_spread;
                if earlyV1(i, size(S,2)-j) < V_call(i,size(S,2)-j)
                    V_call(i,size(S,2)-j) = earlyV1(i, size(S,2)-j);
                    earlyT1 = j;
                end
                earlyV2(i, size(S,2)-j) = S(i,size(S,2)-j) - K_real(1,T-j) - initial_spread;
                if earlyV2(i, size(S,2)-j) > V_put(i,size(S,2)-j)
                    V_put(i,size(S,2)-j) = earlyV2(i, size(S,2)-j);
                    earlyT2 = j;
                end
            end
        end
    end

    date_using(zz,1) = date_full(T,1);
    if earlyT1 == 0
        early{1,zz} = cell(0);
    else
        early{1,zz} = date_full(T-earlyT1,1);
    end
    if earlyT2 == 0
        early{2,zz} = cell(0);
    else
        early{2,zz} = date_full(T-earlyT2,1);
    end
    spread(:,zz) = [V_call(1,1);V_put(1,1)];
end
spread = spread';
plot(spread);figure(gcf);

%% rearrange
window = 12/interval;
for jj = 1 : size(spread,2)
    kk = 1;
    for ii = 1 : floor(size(spread,1)/window)
        spread_temp(ii,jj) = mean(spread(kk:kk+window-1,jj)) * window;
        kk = kk + window; 
    end
end